/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-18 06:43:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addExam_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1688383492314L));
    _jspx_dependants.put("jar:file:/D:/Documents/struts/ExamCreationApp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ExamWizard/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Add exam</title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"public/styles/addExam.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"public/styles/adminHome.css\" />\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\"\r\n");
      out.write("    />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 
   // Retrieve a session attribute
   String username = (String) session.getAttribute("username");

      out.write("\r\n");
      out.write("  <nav class=\"sidebar\">\r\n");
      out.write("    <a href=\"#\" class=\"logo\">\r\n");
      out.write("      <i class=\"fa-solid fa-gauge fa-spin\"></i>\r\n");
      out.write("      Dashboard\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"menu-content\">\r\n");
      out.write("      <ul class=\"menu-items\">\r\n");
      out.write("        <li class=\"item\">\r\n");
      out.write("          <a href=\"profile.do\">\r\n");
      out.write("            <i class=\"fa-solid fa-address-card\"></i>\r\n");
      out.write("            Profile</a>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <li class=\"item\">\r\n");
      out.write("          <a href=\"studentPage.do\">\r\n");
      out.write("            <i class=\"fa-solid fa-users\"></i>\r\n");
      out.write("            Student Informations</a>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <li class=\"item selected-item\">\r\n");
      out.write("          <a href=\"addExamPage.do\">\r\n");
      out.write("            <i class=\"fa-solid fa-book-open\"></i>\r\n");
      out.write("            Examination</a>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <li class=\"item\">\r\n");
      out.write("          <a href=\"logout.do\">\r\n");
      out.write("            <i class=\"fa-solid fa-right-from-bracket\"></i>\r\n");
      out.write("            Logout</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <nav class=\"navbar\">\r\n");
      out.write("    <i class=\"fa-solid fa-bars\" id=\"sidebar-close\"></i>\r\n");
      out.write("    <div class=\"hellotext\">Hello ");
      out.print( username );
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <main class=\"main\">\r\n");
      out.write("    <h1>Exam panel</h1>\r\n");
      out.write("    <div class=\"exam-input\">\r\n");
      out.write("      <form action=\"addExam.do\">\r\n");
      out.write("        <h2>Create Exam</h2>\r\n");
      out.write("         <input type=\"text\" name=\"eid\" value=\"5\" style=\"display:none;\" />\r\n");
      out.write("        <div class=\"exam-card-header\">\r\n");
      out.write("          <input type=\"text\" name=\"etitle\" class=\"exam-title-input\" placeholder=\"Exam title\" />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"exam-card-body\">\r\n");
      out.write("          <div class=\"body-time\">\r\n");
      out.write("            <div class=\"exam-card-body-item\" style=\"border-right: 2px solid rgba(0, 0, 0, 0.472)\">\r\n");
      out.write("              <h5>Opening time</h5>\r\n");
      out.write("              <input type=\"datetime-local\"  class=\"starttime\" name=\"estart\" value=\"2000-01-01T05:40:00\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"exam-card-body-item\">\r\n");
      out.write("              <h5>Closing Time</h5>\r\n");
      out.write("              <input type=\"datetime-local\"  class=\"endtime\" name=\"eend\" value=\"2000-01-01T05:40:00\" />\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"duration\">\r\n");
      out.write("            <h3>Exam Duration(Min)</h3>\r\n");
      out.write("            <input type=\"text\" name=\"eduration\"  value=\"30\" />\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input type=\"submit\" class=\"create-button\" />\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card-holder\">\r\n");
      out.write("     ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"public/js/addExam.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/addExam.jsp(91,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("exam");
      // /WEB-INF/views/addExam.jsp(91,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/addExam.jsp(91,5) '${examList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${examList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("     <div class=\"exam-card\">\r\n");
            out.write("\r\n");
            out.write("        <div class=\"exam-card-header\">\r\n");
            out.write("          <h2> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.etitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h2>\r\n");
            out.write("          <input type=\"text\" class=\"eid\"  id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.eid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("-id\" name=\"eid\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.eid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"display: none\" />\r\n");
            out.write("        </div>\r\n");
            out.write("        <div class=\"exam-card-body\">\r\n");
            out.write("          <div class=\"body-time\">\r\n");
            out.write("            <div class=\"exam-card-body-item\" style=\"border-right: 2px solid rgba(0, 0, 0, 0.472)\">\r\n");
            out.write("              <h5>Opening time</h5>\r\n");
            out.write("              <input type=\"datetime-local\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.eid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("-st\" class=\"starttime\" name=\"estart\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.estart}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("                disabled />\r\n");
            out.write("            </div>\r\n");
            out.write("            <div class=\"exam-card-body-item\">\r\n");
            out.write("              <h5>Closing Time</h5>\r\n");
            out.write("              <input type=\"datetime-local\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.eid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("-et\" class=\"endtime\" name=\"eend\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.eend}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("                disabled />\r\n");
            out.write("            </div>\r\n");
            out.write("          </div>\r\n");
            out.write("          <div class=\"duration\">\r\n");
            out.write("            <h3>Exam Duration(Min)</h3>\r\n");
            out.write("            <input type=\"text\" name=\"eduration\"  id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.eid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("-dur\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.eduration}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" disabled />\r\n");
            out.write("          </div>\r\n");
            out.write("          <div class=\"button-area\">\r\n");
            out.write("            <div class=\"top-button\">\r\n");
            out.write("              <button class=\"exambutton\" style=\"background-color: rgba(255, 78, 13, 0.911)\"\r\n");
            out.write("               onclick=\"window.location.replace('studentForExam.do?eid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.eid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\"\r\n");
            out.write("              >\r\n");
            out.write("                Add Student\r\n");
            out.write("              </button>\r\n");
            out.write("              <button class=\"exambutton\" style=\"background-color: rgba(13, 134, 255, 0.911)\">\r\n");
            out.write("                Add Question\r\n");
            out.write("              </button>\r\n");
            out.write("            </div>\r\n");
            out.write("            <div class=\"bottom-button\">\r\n");
            out.write("              <button class=\"exambutton\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.eid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("-but\" style=\"background-color: rgba(255, 39, 39, 0.911)\"\r\n");
            out.write("                onclick=\"changeExamCard('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exam.eid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\">\r\n");
            out.write("                Edit Exam\r\n");
            out.write("              </button>\r\n");
            out.write("            </div>\r\n");
            out.write("          </div>\r\n");
            out.write("        </div>\r\n");
            out.write("      </div>\r\n");
            out.write("     \r\n");
            out.write("      ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
