/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-20 11:05:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addQuestions_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1688383492314L));
    _jspx_dependants.put("jar:file:/D:/Documents/struts/ExamCreationApp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ExamWizard/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Add Questions</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"public/styles/addQuestions.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"header\">Exam code:  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </div>\r\n");
      out.write("    <div class=\"more-qs\">\r\n");
      out.write("      <a href=\"./allQuestions\">Add from previous questions</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("      <form id=\"mcq-form\"  action=\"submitQuestions.do\">\r\n");
      out.write("        <input\r\n");
      out.write("             \r\n");
      out.write("              type=\"text\"\r\n");
      out.write("              id=\"option-a-image\"\r\n");
      out.write("              name=\"eid\"\r\n");
      out.write("              value= \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("              style=\"display:none;\"\r\n");
      out.write("            />\r\n");
      out.write("        <div class=\"question-container\">\r\n");
      out.write("          <h2 style=\"text-align: center\">ADD QUESTIONS</h2>\r\n");
      out.write("          <div class=\"question-section\">\r\n");
      out.write("            <label for=\"question1\">Question:</label>\r\n");
      out.write("            <textarea\r\n");
      out.write("              type=\"text\"\r\n");
      out.write("              id=\"question1\"\r\n");
      out.write("              name=\"q_text\"\r\n");
      out.write("              placeholder=\"Enter the question\"\r\n");
      out.write("              oninput=\"autoResizeTextarea(this)\"\r\n");
      out.write("              required\r\n");
      out.write("            ></textarea>\r\n");
      out.write("            <input\r\n");
      out.write("              class=\"file-input\"\r\n");
      out.write("              type=\"file\"\r\n");
      out.write("              id=\"option_a_image\"\r\n");
      out.write("              name=\"q-image\"\r\n");
      out.write("              onchange=\"handleFileInputChange(this)\"\r\n");
      out.write("            />\r\n");
      out.write("            <!-- <img id=\"preview-image\" class=\"preview-image\" src=\"\" alt=\"Preview Image\" /> -->\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"option-section\">\r\n");
      out.write("            <div class=\"option\">\r\n");
      out.write("              <label for=\"option-a\">\r\n");
      out.write("              	<div class=\"round-option\">A</div>\r\n");
      out.write("              </label>\r\n");
      out.write("              <input\r\n");
      out.write("                type=\"text\"\r\n");
      out.write("                class=\"option-input\"\r\n");
      out.write("                id=\"option-a-text\"\r\n");
      out.write("                name=\"option_a_text\"\r\n");
      out.write("                placeholder=\"Enter option A\"\r\n");
      out.write("                required\r\n");
      out.write("              />\r\n");
      out.write("              <input\r\n");
      out.write("                class=\"file-input\"\r\n");
      out.write("                type=\"file\"\r\n");
      out.write("                id=\"option-a-image\"\r\n");
      out.write("                name=\"option_a_image\"\r\n");
      out.write("                onchange=\"handleFileInputChange(this)\"\r\n");
      out.write("              />\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"option\">\r\n");
      out.write("              <label for=\"option-b\"><div class=\"round-option\">B</div></label>\r\n");
      out.write("              <input\r\n");
      out.write("                type=\"text\"\r\n");
      out.write("                class=\"option-input\"\r\n");
      out.write("                id=\"option-b-text\"\r\n");
      out.write("                name=\"option_b_text\"\r\n");
      out.write("                placeholder=\"Enter option B\"\r\n");
      out.write("                required\r\n");
      out.write("              />\r\n");
      out.write("              <input\r\n");
      out.write("                class=\"file-input\"\r\n");
      out.write("                type=\"file\"\r\n");
      out.write("                id=\"option-b-image\"\r\n");
      out.write("                name=\"option_b_image\"\r\n");
      out.write("                onchange=\"handleFileInputChange(this)\"\r\n");
      out.write("              />\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"option\">\r\n");
      out.write("              <label for=\"option-c\"><div class=\"round-option\">C</div></label>\r\n");
      out.write("              <input\r\n");
      out.write("                type=\"text\"\r\n");
      out.write("                class=\"option-input\"\r\n");
      out.write("                id=\"option-c-text\"\r\n");
      out.write("                name=\"option_c_text\"\r\n");
      out.write("                placeholder=\"Enter option C\"\r\n");
      out.write("                required\r\n");
      out.write("              />\r\n");
      out.write("              <input\r\n");
      out.write("                class=\"file-input\"\r\n");
      out.write("                type=\"file\"\r\n");
      out.write("                id=\"option-c-image\"\r\n");
      out.write("                name=\"option_c_image\"\r\n");
      out.write("                onchange=\"handleFileInputChange(this)\"\r\n");
      out.write("              />\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"option\">\r\n");
      out.write("              <label for=\"option-d\"><div class=\"round-option\">D</div></label>\r\n");
      out.write("              <input\r\n");
      out.write("                type=\"text\"\r\n");
      out.write("                class=\"option-input\"\r\n");
      out.write("                id=\"option-d-text\"\r\n");
      out.write("                name=\"option_d_text\"\r\n");
      out.write("                placeholder=\"Enter option D\"\r\n");
      out.write("                required\r\n");
      out.write("              />\r\n");
      out.write("              <input\r\n");
      out.write("                class=\"file-input\"\r\n");
      out.write("                type=\"file\"\r\n");
      out.write("                id=\"option-d-image\"\r\n");
      out.write("                name=\"option_d_image\"\r\n");
      out.write("                onchange=\"handleFileInputChange(this)\"\r\n");
      out.write("              />\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"correct-option\">\r\n");
      out.write("            <label for=\"answer\">Correct answer</label>\r\n");
      out.write("            <select class=\"custom-select\" name=\"answer\" id=\"answer\">\r\n");
      out.write("              <option value=\"a\">Option A</option>\r\n");
      out.write("              <option value=\"b\">Option B</option>\r\n");
      out.write("              <option value=\"c\">Option C</option>\r\n");
      out.write("              <option value=\"d\">Option D</option>\r\n");
      out.write("            </select>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"correct-option\">\r\n");
      out.write("            <label for=\"answer\">Question marks</label>\r\n");
      out.write("            <select class=\"custom-select\" name=\"marks\" id=\"answer\">\r\n");
      out.write("              <option value=\"1\" >1</option>\r\n");
      out.write("              <option value=\"2\">2</option>\r\n");
      out.write("              <option value=\"3\">3</option>\r\n");
      out.write("              <option value=\"4\">4</option>\r\n");
      out.write("              <option value=\"5\">5</option>\r\n");
      out.write("            </select>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div style=\"display: flex; justify-content: center; margin-top: 20px\">\r\n");
      out.write("            <button class=\"add-qs-button\" type=\"submit\" class=\"submit-btn\">\r\n");
      out.write("              Add Questions\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"box2\">\r\n");
      out.write("      <form\r\n");
      out.write("        action=\"uploadQuestionCSV.do\"\r\n");
      out.write("        method=\"post\"\r\n");
      out.write("        enctype=\"multipart/form-data\"\r\n");
      out.write("      >\r\n");
      out.write("       <h2>Add bulk questions</h2>\r\n");
      out.write("        <input type=\"text\" name=\"eid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  style=\"display: none;\">\r\n");
      out.write("        <input type=\"file\" class=\"csv-uploader\" name=\"file\" accept=\".csv\" />\r\n");
      out.write("        <input type=\"submit\" value=\"Upload csv\" class=\"upload-button\" />\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("     <div id=\"prev_problems\">\r\n");
      out.write("      <h2 style=\"text-align: center\">OTHER QUESTIONS</h2>\r\n");
      out.write("      <div id=\"problem-section\">\r\n");
      out.write("       ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/addQuestions.jsp(170,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("question");
      // /WEB-INF/views/addQuestions.jsp(170,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/addQuestions.jsp(170,7) '${qsSet}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${qsSet}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("        <div id=\"problem\" >\r\n");
            out.write("        <h3>Question </h3>\r\n");
            out.write("	        <div class=\"question\">\r\n");
            out.write("	            <p class=\"qtext\"> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${question.getQtext() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </p>\r\n");
            out.write("	            <label>\r\n");
            out.write("	            <input type=\"radio\" name=\"qs\" onchange=\"handleRadioChange(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\"   disable />\r\n");
            out.write("	            <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${question.getOptions().get(0).getOtext() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </span>\r\n");
            out.write("	            </label>\r\n");
            out.write("	            <label>\r\n");
            out.write("	            <input type=\"radio\" name=\"qs\" onchange=\"handleRadioChange(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\"  disable />\r\n");
            out.write("	            <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${question.getOptions().get(1).getOtext() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </span>\r\n");
            out.write("	            </label>\r\n");
            out.write("	            <label>\r\n");
            out.write("	            <input type=\"radio\" name=\"qs\" onchange=\"handleRadioChange(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\"  disable />\r\n");
            out.write("	            <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${question.getOptions().get(2).getOtext() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </span>\r\n");
            out.write("	            </label>\r\n");
            out.write("	            <label>\r\n");
            out.write("	            <input type=\"radio\" name=\"qs\" onchange=\"handleRadioChange(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\"  disable />\r\n");
            out.write("	            <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${question.getOptions().get(3).getOtext() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </span>\r\n");
            out.write("	            </label>\r\n");
            out.write("	        </div>\r\n");
            out.write("	        <div class=\"button-section\">\r\n");
            out.write("	        <button class=\"change-button2\" id=\"delete-button\"  > Delete </button>\r\n");
            out.write("	      </div>\r\n");
            out.write("	      <hr />\r\n");
            out.write("	      </div>\r\n");
            out.write("	    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
