/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-07-13 11:06:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"ISO-8859-1\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>ExamWizard</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"public/styles/index.css\" />\r\n");
      out.write("    <!-- Unicons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://unicons.iconscout.com/release/v4.0.0/css/line.css\" />\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	 <!-- Header -->\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("      <nav class=\"nav\">\r\n");
      out.write("        <a href=\"#\" class=\"nav_logo\">CodingLab</a>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"nav_items\">\r\n");
      out.write("          <li class=\"nav_item\">\r\n");
      out.write("            <a href=\"#\" class=\"nav_link\">Home</a>\r\n");
      out.write("            <a href=\"#\" class=\"nav_link\">Product</a>\r\n");
      out.write("            <a href=\"#\" class=\"nav_link\">Services</a>\r\n");
      out.write("            <a href=\"#\" class=\"nav_link\">Contact</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <button class=\"button\" id=\"form-open\">Login</button>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Home -->\r\n");
      out.write("    <section class=\"home\">\r\n");
      out.write("      <div class=\"form_container\">\r\n");
      out.write("        <i class=\"uil uil-times form_close\"></i>\r\n");
      out.write("        <!-- Login From -->\r\n");
      out.write("        <div class=\"form login_form\">\r\n");
      out.write("          <form id =\"loginForm\" action=\"login.do\" method=\"post\">\r\n");
      out.write("            <h2>Login</h2>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"input_box\">\r\n");
      out.write("              <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"Enter your email\" required />\r\n");
      out.write("              <i class=\"uil uil-envelope-alt email\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input_box\">\r\n");
      out.write("              <input type=\"password\" id=\"uroll\" name=\"uroll\" placeholder=\"Enter your password\" required />\r\n");
      out.write("              <i class=\"uil uil-lock password\"></i>\r\n");
      out.write("              <i class=\"uil uil-eye-slash pw_hide\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("		 <!-- <div class=\"option_field\">\r\n");
      out.write("              <span class=\"checkbox\">\r\n");
      out.write("                <input type=\"checkbox\" id=\"check\" />\r\n");
      out.write("                <label for=\"check\">Remember me</label>\r\n");
      out.write("              </span>\r\n");
      out.write("              <a href=\"#\" class=\"forgot_pw\">Forgot password?</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          -->   \r\n");
      out.write("\r\n");
      out.write("            <button class=\"button\" type=\"submit\" >Login Now</button>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"login_signup\">Don't have an account? <a href=\"#\" id=\"signup\">Signup</a></div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Signup From -->\r\n");
      out.write("        <div class=\"form signup_form\">\r\n");
      out.write("          <form id=\"signupForm\" action=\"signup.do\" method=\"post\">\r\n");
      out.write("            <h2>Signup</h2>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"input_box\">\r\n");
      out.write("              <input type=\"text\"  id=\"uname\" name=\"uname\" placeholder=\"Enter your name\" required />\r\n");
      out.write("              <i class=\"uil uil-envelope-alt name\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input_box\">\r\n");
      out.write("              <input type=\"email\"  id=\"email\" name=\"email\" placeholder=\"Enter your email\" required />\r\n");
      out.write("              <i class=\"uil uil-envelope-alt email\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input_box\">\r\n");
      out.write("              <input type=\"text\" id=\"uroll\" name=\"uroll\" placeholder=\"Enter RollNo.\" required />\r\n");
      out.write("              <i class=\"uil uil-user uroll_icon\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input_box\">\r\n");
      out.write("              <input type=\"date\" id=\"dob\" name=\"dob\" placeholder=\"Enter your date of birth\" required />\r\n");
      out.write("            <i class=\"uil uil-calendar-alt date\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"button\">Signup Now</button>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"login_signup\">Already have an account? <a href=\"#\" id=\"login\">Login</a></div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"public\\js\\index.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
